#page title
page_title                                :     Clever Jacks                                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6450907461                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/SequenceCardsLogo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Clever Jacks                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A Multiplayer Board-Cards game.!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kruthay Donapati                                
your_link                                 : https://www.linkedin.com/in/kruthay                     
your_city                                 : Fairfax                                
email_address                             : kruthayreddy@gmail.com
facebook_username                         :                                           
instagram_username                        : kruthay_
twitter_username                          : kruthay
github_username                           : kruthay
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Clever Jacks
    description                           : The Multiplayer Board-Cards game that guarantees hours of engaging entertainment!
    fontawesome_icon_name                 : magic
    
  - title                                 : Game Modes
    description                           : Challenge your friends in 2-player or 3-player modes, or take on the computer in a head-to-head battle.
    fontawesome_icon_name                 : mobile

  - title                                 : Game Center
    description                           : Enjoy easy sign-in with Game Center and play with friends or get matched automatically for a quick match.
    fontawesome_icon_name                 : play

  - title                                 : Easy to learn
    description                           : New to the game? Check out the Rules page for a clear guide. Clever Jacks features a game board, unique player coins, and player cards. 
    fontawesome_icon_name                 : book

  - title                                 : Strategy
    description                           : Strategically place your coin on empty cards to outmaneuver your opponents..
    fontawesome_icon_name                 : chess-queen
  
  - title                                 : Super Powers
    description                           : Experience the unique abilities of the Jacks – One-Eyed Jacks eliminate opponent coins, while Two-Eyed Jacks add coins.
    fontawesome_icon_name                 : star

 - title                                 : Chat
    description                           : Chat with your friends during the game. 
    fontawesome_icon_name                 : comments
    
  - title                                 : Free
    description                           : Best of all, Clever Jacks is free and ad-free. Dive into strategic fun with Clever Jacks now!
    fontawesome_icon_name                 : heart

  - title                                 : Indefinite Time
    description                           : You can take indefinite time to make your turn.!
    fontawesome_icon_name                 : clock

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
